version: "3.9"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
      # - './initial.sql:/docker-entrypoint-initdb.d/initial.sql'
